### ISSUE TITLE
Adicionar campo de `Dia` para uma entrada.

### ISSUE THREAD

**Issue by marclerodrigues** [marclerodrigues/carambolo#4]
![photo5170656620680685644](https://user-images.githubusercontent.com/8514920/67147212-47b45800-f269-11e9-9468-f8589d05e3f6.jpg)

**Comment by PacoLuna1** [comment]
Can I try It?

**Comment by marclerodrigues** [comment]
go ahead @PacoLuna1

**Comment by PacoLuna1** [comment]
Here it is #16
