### ISSUE TITLE
Adicionar campo de `hora` para uma entrada

### ISSUE THREAD

**Issue by marclerodrigues** [marclerodrigues/carambolo#5]
![photo5170656620680685644](https://user-images.githubusercontent.com/8514920/67147221-74686f80-f269-11e9-922e-3970709f1576.jpg)

**Comment by PacoLuna1** [comment]
@marclerodrigues Can I try It?

**Comment by marclerodrigues** [comment]
go ahead @PacoLuna1

**Comment by PacoLuna1** [comment]
@marclerodrigues  Here it is #17
